### ISSUE TITLE
Return error when registering Storj account with invalid email or password

### ISSUE THREAD

**Issue by jkawamoto** [GooBox/goobox-sync-storj#80] opened 2018-01-17 17:40 UTC
Originally posted in https://github.com/GooBox/goobox-community-gui/issues/48

**Comment by kaloyan-raev** [comment] 2018-01-17 17:43
It currently does.

Didn't you see this entries from the log?

```
Command result sent: {"status":"error","message":"Invalid email"}
```

```
Command result sent: {"status":"error","message":"Email is already registered"}
```

**Comment by jkawamoto** [comment] 2018-01-17 17:56
So, this one isn't issue and we can close both of them, can't we? I think using other log level such as WARN or DEBUG is better to know which log entry is an issue or not.

**Comment by kaloyan-raev** [comment] 2018-01-17 18:21
I am just saying the issue is not here. I am sure GUI v0.0.5 shows the error in a dialog. Perhaps, there is a regression in the GUI in the latest snapshot.

**Comment by MeijeSibbel** [comment] 2018-01-31 22:15
I hink we can close this one as its already implemented.

**Closed as completed by MeijeSibbel** 2018-01-31 22:15 UTC
